-- Discard tablespaces and drop corrupted tables

ALTER TABLE admins DISCARD TABLESPACE;
DROP TABLE IF EXISTS admins;

ALTER TABLE entrepreneurs DISCARD TABLESPACE;
DROP TABLE IF EXISTS entrepreneurs;

ALTER TABLE investments DISCARD TABLESPACE;
DROP TABLE IF EXISTS investments;

ALTER TABLE investors DISCARD TABLESPACE;
DROP TABLE IF EXISTS investors;

ALTER TABLE otp_verifications DISCARD TABLESPACE;
DROP TABLE IF EXISTS otp_verifications;

ALTER TABLE pitches DISCARD TABLESPACE;
DROP TABLE IF EXISTS pitches;

ALTER TABLE users DISCARD TABLESPACE;
DROP TABLE IF EXISTS users;
